CREATE TABLE PESSOA(
COD_PESSOA INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45),
CPF CHAR(11),
GENERO CHAR(1),
EMAIL VARCHAR(40),
CELULAR VARCHAR(11),
TELEFONE VARCHAR(10),
COD_ENDERECO INT,
CONSTRAINT PK_PESSOA PRIMARY KEY(COD_PESSOA)
);

CREATE TABLE ALUNO(
COD_ALUNO INT NOT NULL AUTO_INCREMENT,
RGM INT,
SEMESTRE INT,
PERIODO VARCHAR(10),
FALTAS_DICIPLINA INT DEFAULT(0),
NOTAS_DISCIPLINA INT DEFAULT(0),
COD_PESSOA INT,
CONSTRAINT PK_ALUNO PRIMARY KEY(COD_ALUNO, RGM),
CONSTRAINT FK_ALUNO FOREIGN KEY (COD_PESSOA) REFERENCES PESSOA(COD_PESSOA)
);

CREATE TABLE ENDERECO(
COD_ENDERECO INT NOT NULL AUTO_INCREMENT,
CEP CHAR(8),
ENDERECO VARCHAR(30),
BAIRRO VARCHAR(20),
COMPLEMENTO VARCHAR(20),
NUMERO VARCHAR(6),
UF CHAR(2),
CIDADE VARCHAR(20),
CONSTRAINT PK_ENDERECO PRIMARY KEY (COD_ENDERECO, CEP)
);


ALTER TABLE PESSOA
ADD CONSTRAINT FK_ENDERECO FOREIGN KEY (COD_ENDERECO) REFERENCES PESSOA(COD_PESSOA);

select * from pessoa;

select * from aluno;

delete from pessoa where COD_PESSOA > 0;

delete from aluno where COD_aluno > 0;
