CREATE TABLE PESSOA(
COD_PESSOA INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45) NOT NULL,
GENERO VARCHAR(9) NOT NULL,
CPF CHAR(11) NOT NULL,
EMAIL VARCHAR(40),
CELULAR CHAR(11),
TELEFONE CHAR(10),
COD_ENDERECO INT,
COD_CURSO INT,
CONSTRAINT PK_PESSOA PRIMARY KEY(COD_PESSOA)
);

CREATE TABLE ALUNO(
COD_ALUNO INT NOT NULL AUTO_INCREMENT,
RGM INT NOT NULL,
SEMESTRE INT NOT NULL,
PERIODO VARCHAR(10),
FALTAS_DICIPLINA INT DEFAULT(0),
NOTAS_DISCIPLINA INT DEFAULT(0),
COD_PESSOA INT,
CONSTRAINT PK_ALUNO PRIMARY KEY(COD_ALUNO, RGM)
);

CREATE TABLE CURSO(
COD_CURSO INT NOT NULL AUTO_INCREMENT,
NOME_CURSO VARCHAR(45) NOT NULL,
CAMPUS VARCHAR(20) NOT NULL,
CONSTRAINT PK_CURSO PRIMARY KEY(COD_CURSO)
);

CREATE TABLE ENDERECO(
COD_ENDERECO INT NOT NULL AUTO_INCREMENT,
CEP CHAR(8) NOT NULL,
ENDERECO VARCHAR(30) NOT NULL,
BAIRRO VARCHAR(20) NOT NULL,
COMPLEMENTO VARCHAR(20),
NUMERO VARCHAR(6) NOT NULL,
UF CHAR(2) NOT NULL,
CIDADE VARCHAR(20) NOT NULL,
CONSTRAINT PK_ENDERECO PRIMARY KEY (COD_ENDERECO, CEP)
);

/*ALTER TABLE ALUNO
ADD CONSTRAINT FK_ALUNO FOREIGN KEY (COD_PESSOA) REFERENCES PESSOA(COD_PESSOA)*/

/*ALTER TABLE ALUNO
ADD CONSTRAINT FK_CURSO FOREIGN KEY (COD_CURSO) REFERENCES CURSO(COD_CURSO)*/

/*ALTER TABLE PESSOA
ADD CONSTRAINT FK_ENDERECO FOREIGN KEY (COD_ENDERECO) REFERENCES ENDERECO(COD_ENDERECO)*/

