CREATE TABLE ENDERECO(
COD_ENDERECO INT NOT NULL AUTO_INCREMENT,
CEP CHAR(8),
ENDERECO VARCHAR(30),
BAIRRO VARCHAR(20),
COMPLEMENTO VARCHAR(20),
NUMERO VARCHAR(6),
UF CHAR(2),
CIDADE VARCHAR(20),
CONSTRAINT PK_ENDERECO PRIMARY KEY (COD_ENDERECO, CEP)
);

CREATE TABLE PESSOA(
COD_PESSOA INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45),
CPF CHAR(11),
NASCIMENTO CHAR(9),
GENERO CHAR(1),
EMAIL VARCHAR(40),
CELULAR VARCHAR(11),
TELEFONE VARCHAR(10),
COD_ENDERECO INT,
CONSTRAINT PK_PESSOA PRIMARY KEY(COD_PESSOA),
CONSTRAINT FK_ENDERECO FOREIGN KEY (COD_ENDERECO) REFERENCES ENDERECO(COD_ENDERECO)
);

CREATE TABLE ALUNO(
COD_ALUNO INT NOT NULL AUTO_INCREMENT,
RGM INT,
PERIODO VARCHAR(10),
CAMPUS VARCHAR(8),
FALTAS_DICIPLINA INT DEFAULT(0),
NOTAS_DISCIPLINA INT DEFAULT(0),
COD_PESSOA INT,
CONSTRAINT PK_ALUNO PRIMARY KEY(COD_ALUNO, RGM),
CONSTRAINT FK_ALUNO FOREIGN KEY (COD_PESSOA) REFERENCES PESSOA(COD_PESSOA)
);

CREATE TABLE UF(
COD_UF INT AUTO_INCREMENT,
SIGLA CHAR(2),
CONSTRAINT PK_UF PRIMARY KEY (COD_UF)
);

CREATE TABLE CURSO(
COD_CURSO INT AUTO_INCREMENT,
NOME_CURSO VARCHAR(30),
CONSTRAINT PK_CURSO PRIMARY KEY (COD_CURSO)
);

CREATE TABLE DISCIPLINA(

COD_DISCIPLINA INT AUTO_INCREMENT,
NOME_DISCIPLINA VARCHAR(30),
COD_CURSO INT,
CONSTRAINT PK_DISCIPLINA PRIMARY KEY (COD_DISCIPLINA),
CONSTRAINT FK_CURSO FOREIGN KEY (COD_CURSO) REFERENCES CURSO(COD_CURSO)
); 

CREATE TABLE DISCIPLINAALUNO(

RGM INT,
FALTAS INT,
NOTA FLOAT,
SEMESTRE CHAR(9),
COD_DISCIPLINA INT
);

INSERT INTO UF(SIGLA) VALUES ("AC"),("AL"),("AP"),("AM"),("BA"),("CE"),("DF"),("ES"),("GO"),("MA"),("MT"),("MS"),("MG"),("PA"),("PB"),("PR"),("PE"),("PI"),("RJ"),("RN"),("RS"),("RO"),("RR"),("SC"),("SP"),("SE"),("TO");

INSERT INTO CURSO(NOME_CURSO)curso VALUES ("Análise de Sistemas"), ("Banco de Dados"), ("Ciências da Computação"), ("Redes");

INSERT INTO DISCIPLINA(NOME_DISCISPLINA, COD_CURSO) VALUES("Sistemas Operacionais", 1), ("Técninas de Programação", 1), ("Algoritimos", 3), ("Cabeamento", 4);

select disciplina.NOME_DISCISPLINA
from disciplina, curso
where curso.COD_CURSO = "Análise de Sistemas";

select * from pessoa;

select * from aluno;

select * from endereco;

select * from curso;

delete from aluno where COD_aluno > 0;

delete from pessoa where COD_PESSOA > 0;

delete from endereco where COD_ENDERECO > 0;